site_name: Re:Produce
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
palette:
    # try other colors from https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: blue
    accent: blue
font:
    # See available fonts from https://fonts.google.com/
    text: Arima Madurai
    code: Roboto Mono
features:
    # See more about the navigation at https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs
custom_dir: 'overrides'
plugins:
  - search
 # - git-revision-date:
  #    enabled_if_env: CI
extra_css:
  - https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css
  - stylesheets/extra.css






